name: LSIF
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate LSIF Data
        uses: sourcegraph/lsif-go-action@0.1.0-dogfood
        with:
          verbose: 'true'
      - name: Upload LSIF data
        uses: sourcegraph/lsif-upload-action@0.1.0-dogfood
        with:
          upload_token: ${{ secrets.LSIF_UPLOAD_TOKEN }}
